[package]
name = "example"
version = "0.1.0"
authors = ["anekos <anekos@snca.net>"]
edition = "2018"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
image-meta = { path = "../" }
regex = "*"
